# Generated by Django 5.2.8 on 2025-11-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
